# https://query.wikidata.org/
#defaultView:Table
SELECT ?item ?itemLabel ?country ?countryLabel ?place ?placeLabel ?language ?languageLabel ?pic ?offurl
WHERE
{
?item wdt:P31 wd:Q11032 .
OPTIONAL {?item wdt:P17 ?country .}
OPTIONAL {?item wdt:P291 ?place .}
OPTIONAL {?item wdt:P407 ?language .}
OPTIONAL {?item wdt:P154 ?pic .}
?item wdt:P856 ?offurl
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
